/**
 * Report exports — the PDF writer (pdfkit, pure JavaScript; no Chromium, so it runs in a Vercel
 * Node function with no binary and no cold-start penalty).
 *
 * Spec: "PDF: printable, shop + date range + generated-at + generated-by header, page numbers."
 * Every page carries the header block and the table's column header; the footer "Page n / N" is
 * written in a final pass over the buffered pages (`bufferPages: true`), because N is only known
 * once the last row is placed.
 *
 * Cells are formatted by the SAME `formatCell` as the CSV, so both files say the same thing.
 *
 * DEPLOY NOTE. pdfkit reads its standard-font metrics (.afm files) from its own package directory
 * at runtime. Bundled, those reads point at files the tracer never copied — a PDF that renders
 * locally and 500s on Vercel. `serverExternalPackages: ["pdfkit"]` in next.config.ts keeps it a
 * plain Node require, so the tracer ships the package directory whole. tests/report-pdf.test.ts
 * renders a real document so a broken install fails in CI, not in production.
 *
 * FONTS. Only the 14 standard PDF fonts are used (Helvetica). They are WinAnsi-encoded: Latin-1
 * covers Spanish (á é í ó ú ñ ü ¿ ¡); anything outside it is replaced by "?" rather than being
 * written as garbage.
 */
import "server-only";
import PDFDocument from "pdfkit";
import { formatCell, type ExportColumn, type ExportRow } from "@/lib/report-export-shared";
import { formatTime } from "@/lib/i18n/format";
import { serverT } from "@/lib/i18n/server";
import type { Language, TranslationKey } from "@/lib/i18n/types";
import { etCalendarDate } from "@/lib/operational-day";
import { TENANT_NAME } from "@/lib/tenant";

export interface PdfHeader {
  /** Big line: e.g. "Cash reports". */
  title: string;
  /** Small lines under it, already translated: tenant, shop, range, generated at, generated by. */
  lines: string[];
}

export interface PdfTable {
  /** Section heading (the accountant package has one table per section); null = none. */
  heading: string | null;
  columns: readonly ExportColumn[];
  rows: readonly ExportRow[];
  /** Shown when the table has no rows (translated). */
  emptyText: string;
}

export interface PdfOptions {
  /** "Page {n} / {total}" formatter (translated by the caller). */
  pageLabel: (n: number, total: number) => string;
  /** "Columns {i} of {n}" label for a wide table split across pages (translated by the caller). */
  partLabel?: (i: number, n: number) => string;
  /** Tests turn compression off so the content stream can be read. */
  compress?: boolean;
}

const MARGIN = 32;
const FONT_SIZE = 7;
/** One text line at FONT_SIZE, the gap under a row, the cell padding, the footer band. */
const LINE = 9;
const ROW_GAP = 3;
const CELL_PAD = 1.5;
const FOOTER_SPACE = 14;
/** Columns repeated in every part of a wide table (the identifying ones come first in every registry). */
const KEY_COLUMNS = 3;
const HEADER_FONT = "Helvetica-Bold";
const BODY_FONT = "Helvetica";
const MIN_COL = 34;
const MAX_COL = 200;

/** WinAnsi-safe text: keep printable ASCII, Latin-1 and the ellipsis; replace everything else. */
export function pdfSafe(text: string): string {
  return text.replace(/\s+/g, " ").replace(/[^\x20-\x7E -ÿ…]/g, "?");
}

/** Header labels read better with spaces; the keys stay the CSV contract. */
function headerLabel(key: string): string {
  return key.replaceAll("_", " ");
}

type Doc = InstanceType<typeof PDFDocument>;

function fit(doc: Doc, text: string, width: number): string {
  if (doc.widthOfString(text) <= width) return text;
  let lo = 0;
  let hi = text.length;
  while (lo < hi) {
    const mid = Math.ceil((lo + hi) / 2);
    if (doc.widthOfString(`${text.slice(0, mid)}…`) <= width) lo = mid;
    else hi = mid - 1;
  }
  return `${text.slice(0, lo)}…`;
}

/** Natural width per column (header vs the first 200 cells), clamped to [MIN_COL, MAX_COL]. */
function naturalWidths(doc: Doc, table: PdfTable): number[] {
  return table.columns.map((c) => {
    doc.font(HEADER_FONT).fontSize(FONT_SIZE);
    let w = Math.min(doc.widthOfString(headerLabel(c.key)), 90);
    doc.font(BODY_FONT).fontSize(FONT_SIZE);
    for (const row of table.rows.slice(0, 200)) w = Math.max(w, doc.widthOfString(pdfSafe(formatCell(c.kind, row[c.key]))));
    return Math.min(MAX_COL, Math.max(MIN_COL, w + CELL_PAD * 2));
  });
}

/**
 * WIDE TABLES SPLIT ACROSS PAGES (Astra P2), never squeezed into illegibility: the columns are
 * packed into parts that each fit the page width; every part repeats the identifying columns
 * (the first ones, e.g. business_date + shop) so a part on its own still says which row it is.
 */
export function splitColumns(widths: number[], available: number, keyCount: number): number[][] {
  const all = widths.map((_, i) => i);
  if (widths.reduce((a, b) => a + b, 0) <= available) return [all];
  let keys = all.slice(0, keyCount);
  if (keys.reduce((a, i) => a + widths[i]!, 0) > available * 0.4) keys = [];
  const keyWidth = keys.reduce((a, i) => a + widths[i]!, 0);
  const parts: number[][] = [];
  let current: number[] = [];
  let used = keyWidth;
  for (const i of all.slice(keys.length)) {
    if (current.length > 0 && used + widths[i]! > available) { parts.push([...keys, ...current]); current = []; used = keyWidth; }
    current.push(i);
    used += widths[i]!;
  }
  if (current.length > 0) parts.push([...keys, ...current]);
  return parts;
}

/** Render a report: header block on every page, wrapped cells with variable row heights, "Page n / N". */
export async function renderReportPdf(header: PdfHeader, tables: readonly PdfTable[], options: PdfOptions): Promise<Buffer> {
  const doc: Doc = new PDFDocument({
    size: "LETTER", layout: "landscape", margin: MARGIN, bufferPages: true, compress: options.compress ?? true,
    info: { Title: pdfSafe(header.title) },
  });
  const chunks: Buffer[] = [];
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const width = doc.page.width - MARGIN * 2;
  const bottom = () => doc.page.height - MARGIN - FOOTER_SPACE;

  const drawHeader = () => {
    doc.font(HEADER_FONT).fontSize(12).fillColor("#000").text(pdfSafe(header.title), MARGIN, MARGIN, { width, lineBreak: false });
    doc.font(BODY_FONT).fontSize(8).fillColor("#333");
    let y = MARGIN + 16;
    for (const line of header.lines) {
      doc.text(fit(doc, pdfSafe(line), width), MARGIN, y, { width, lineBreak: false });
      y += 10;
    }
    doc.moveTo(MARGIN, y + 2).lineTo(MARGIN + width, y + 2).strokeColor("#999").lineWidth(0.5).stroke();
    return y + 8;
  };

  const cellHeight = (text: string, w: number) => (text === "" ? LINE : doc.heightOfString(text, { width: w - CELL_PAD * 2 }));
  const rowHeight = (texts: string[], ws: number[], font: string) => {
    doc.font(font).fontSize(FONT_SIZE);
    return Math.max(LINE, ...texts.map((t, i) => cellHeight(t, ws[i]!))) + ROW_GAP;
  };
  const drawRow = (texts: string[], ws: number[], y: number, font: string, h: number) => {
    doc.font(font).fontSize(FONT_SIZE).fillColor("#000");
    let x = MARGIN;
    texts.forEach((t, i) => {
      if (t !== "") doc.text(t, x + CELL_PAD, y, { width: ws[i]! - CELL_PAD * 2 });
      x += ws[i]!;
    });
    doc.moveTo(MARGIN, y + h - 1).lineTo(MARGIN + ws.reduce((a, b) => a + b, 0), y + h - 1).strokeColor("#e2e2e2").lineWidth(0.3).stroke();
  };
  /** The longest word-boundary prefix of `text` that fits `maxH` at width `w`, and the rest. */
  const prefixFitting = (text: string, w: number, maxH: number): [string, string] => {
    if (cellHeight(text, w) <= maxH) return [text, ""];
    const words = text.split(" ");
    let lo = 0;
    let hi = words.length;
    while (lo < hi) {
      const mid = Math.ceil((lo + hi) / 2);
      if (cellHeight(words.slice(0, mid).join(" "), w) <= maxH) lo = mid;
      else hi = mid - 1;
    }
    if (lo === 0) {
      // One word longer than the cell: cut by characters.
      let c = text.length;
      while (c > 1 && cellHeight(text.slice(0, c), w) > maxH) c = Math.floor(c / 2);
      return [text.slice(0, c), text.slice(c)];
    }
    return [words.slice(0, lo).join(" "), words.slice(lo).join(" ")];
  };

  let y = drawHeader();
  const headerBottom = y;
  for (const [index, table] of tables.entries()) {
    const natural = naturalWidths(doc, table);
    const parts = splitColumns(natural, width, KEY_COLUMNS);
    for (const [p, part] of parts.entries()) {
      const cols = part.map((i) => table.columns[i]!);
      const nat = part.map((i) => natural[i]!);
      const total = nat.reduce((a, b) => a + b, 0);
      const ws = total > width ? nat.map((w) => (w / total) * width) : nat;
      const headers = cols.map((c) => headerLabel(c.key));
      const headerH = rowHeight(headers, ws, HEADER_FONT);
      const partText = parts.length > 1 ? (options.partLabel ? options.partLabel(p + 1, parts.length) : `(${p + 1}/${parts.length})`) : "";
      const heading = [table.heading ? pdfSafe(table.heading) : "", pdfSafe(partText)].filter(Boolean).join(" · ");
      if ((index > 0 || p > 0) && y + 16 + headerH + LINE * 3 > bottom()) { doc.addPage(); y = drawHeader(); }
      if (heading) {
        doc.font(HEADER_FONT).fontSize(9).fillColor("#000").text(heading, MARGIN, y + 4, { width, lineBreak: false });
        y += 16;
      }
      drawRow(headers, ws, y, HEADER_FONT, headerH);
      y += headerH;
      const newPage = () => {
        doc.addPage();
        y = drawHeader();
        drawRow(headers, ws, y, HEADER_FONT, headerH);
        y += headerH;
      };
      if (table.rows.length === 0) {
        doc.font(BODY_FONT).fontSize(FONT_SIZE).fillColor("#555").text(pdfSafe(table.emptyText), MARGIN, y, { width, lineBreak: false });
        y += LINE + ROW_GAP;
      }
      for (const row of table.rows) {
        let texts = cols.map((c) => pdfSafe(formatCell(c.kind, row[c.key])));
        // Every cell WRAPS (nothing is ellipsized): a row is as tall as its tallest cell. A row
        // taller than a whole page continues on the next one, so long text survives in full.
        for (;;) {
          const h = rowHeight(texts, ws, BODY_FONT);
          if (y + h <= bottom()) { drawRow(texts, ws, y, BODY_FONT, h); y += h; break; }
          const fresh = bottom() - (headerBottom + headerH);
          if (h <= fresh || bottom() - y < LINE * 3) { newPage(); continue; }
          doc.font(BODY_FONT).fontSize(FONT_SIZE);
          const avail = bottom() - y - ROW_GAP;
          const split = texts.map((t, i) => prefixFitting(t, ws[i]!, avail));
          drawRow(split.map(([a]) => a), ws, y, BODY_FONT, bottom() - y);
          texts = split.map(([, rest]) => rest);
          newPage();
        }
      }
      y += LINE;
    }
  }

  // Footer pass. Writing below the bottom margin makes pdfkit add a page, so the margin is lifted
  // for the footer line and restored.
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const saved = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    doc.font(BODY_FONT).fontSize(8).fillColor("#333")
      .text(pdfSafe(options.pageLabel(i - range.start + 1, range.count)), MARGIN, doc.page.height - MARGIN + 8, { width, align: "right", lineBreak: false });
    doc.page.margins.bottom = saved;
  }
  doc.end();
  return done;
}

/** The PDF header lines (shared by the on-screen export and the package): tenant · shop · range · generated at (ET) · generated by. */
export function pdfHeaderLines(language: Language, args: { shop: string; from: string; to: string; at: Date; by: string }): string[] {
  const t = (key: TranslationKey, values?: Record<string, string | number>) => serverT(language, key, values);
  return [
    TENANT_NAME,
    t("reports.export.header.shop", { shop: args.shop }),
    t("reports.export.header.range", { from: args.from, to: args.to }),
    t("reports.export.header.generated_at", { date: etCalendarDate(args.at.toISOString()), time: formatTime(args.at.toISOString(), language) }),
    t("reports.export.header.generated_by", { name: args.by }),
  ];
}
