/**
 * Report exports — the PDF writer (pdfkit, pure JavaScript; no Chromium, so it runs in a Vercel
 * Node function with no binary and no cold-start penalty).
 *
 * Spec: "PDF: printable, shop + date range + generated-at + generated-by header, page numbers."
 * Every page carries the header block and the table's column header; the footer "Page n / N" is
 * written in a final pass over the buffered pages (`bufferPages: true`), because N is only known
 * once the last row is placed.
 *
 * Cells are formatted by the SAME `formatCell` as the CSV, so both files say the same thing.
 *
 * DEPLOY NOTE. pdfkit reads its standard-font metrics (.afm files) from its own package directory
 * at runtime. Bundled, those reads point at files the tracer never copied — a PDF that renders
 * locally and 500s on Vercel. `serverExternalPackages: ["pdfkit"]` in next.config.ts keeps it a
 * plain Node require, so the tracer ships the package directory whole. tests/report-pdf.test.ts
 * renders a real document so a broken install fails in CI, not in production.
 *
 * FONTS. Only the 14 standard PDF fonts are used (Helvetica). They are WinAnsi-encoded: Latin-1
 * covers Spanish (á é í ó ú ñ ü ¿ ¡); anything outside it is replaced by "?" rather than being
 * written as garbage.
 */
import "server-only";
import PDFDocument from "pdfkit";
import { formatCell, type ExportColumn, type ExportRow } from "@/lib/report-export-shared";
import { formatTime } from "@/lib/i18n/format";
import { serverT } from "@/lib/i18n/server";
import type { Language, TranslationKey } from "@/lib/i18n/types";
import { etCalendarDate } from "@/lib/operational-day";
import { TENANT_NAME } from "@/lib/tenant";

export interface PdfHeader {
  /** Big line: e.g. "Cash reports". */
  title: string;
  /** Small lines under it, already translated: tenant, shop, range, generated at, generated by. */
  lines: string[];
}

export interface PdfTable {
  /** Section heading (the accountant package has one table per section); null = none. */
  heading: string | null;
  columns: readonly ExportColumn[];
  rows: readonly ExportRow[];
  /** Shown when the table has no rows (translated). */
  emptyText: string;
}

export interface PdfOptions {
  /** "Page {n} / {total}" formatter (translated by the caller). */
  pageLabel: (n: number, total: number) => string;
  /** Tests turn compression off so the content stream can be read. */
  compress?: boolean;
}

const MARGIN = 32;
const FONT_SIZE = 7;
const ROW_HEIGHT = 11;
const HEADER_FONT = "Helvetica-Bold";
const BODY_FONT = "Helvetica";
const MIN_COL = 28;
const MAX_COL = 220;

/** WinAnsi-safe text: keep printable ASCII, Latin-1 and the ellipsis; replace everything else. */
export function pdfSafe(text: string): string {
  return text.replace(/\s+/g, " ").replace(/[^\x20-\x7E -ÿ…]/g, "?");
}

/** Header labels read better with spaces; the keys stay the CSV contract. */
function headerLabel(key: string): string {
  return key.replaceAll("_", " ");
}

type Doc = InstanceType<typeof PDFDocument>;

function fit(doc: Doc, text: string, width: number): string {
  if (doc.widthOfString(text) <= width) return text;
  let lo = 0;
  let hi = text.length;
  while (lo < hi) {
    const mid = Math.ceil((lo + hi) / 2);
    if (doc.widthOfString(`${text.slice(0, mid)}…`) <= width) lo = mid;
    else hi = mid - 1;
  }
  return `${text.slice(0, lo)}…`;
}

/** Natural width per column (header vs the first 200 cells), scaled to fit the page width. */
function columnWidths(doc: Doc, table: PdfTable, available: number): number[] {
  const natural = table.columns.map((c) => {
    doc.font(HEADER_FONT).fontSize(FONT_SIZE);
    let w = doc.widthOfString(headerLabel(c.key));
    doc.font(BODY_FONT).fontSize(FONT_SIZE);
    for (const row of table.rows.slice(0, 200)) w = Math.max(w, doc.widthOfString(pdfSafe(formatCell(c.kind, row[c.key]))));
    return Math.min(MAX_COL, Math.max(MIN_COL, w + 6));
  });
  const total = natural.reduce((a, b) => a + b, 0);
  return total <= available ? natural : natural.map((w) => (w / total) * available);
}

/** Render a report: header block on every page, one or more tables, "Page n / N" footers. */
export async function renderReportPdf(header: PdfHeader, tables: readonly PdfTable[], options: PdfOptions): Promise<Buffer> {
  const doc: Doc = new PDFDocument({
    size: "LETTER", layout: "landscape", margin: MARGIN, bufferPages: true, compress: options.compress ?? true,
    info: { Title: pdfSafe(header.title) },
  });
  const chunks: Buffer[] = [];
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const width = doc.page.width - MARGIN * 2;
  const bottom = () => doc.page.height - MARGIN - ROW_HEIGHT * 2;

  const drawHeader = () => {
    doc.font(HEADER_FONT).fontSize(12).fillColor("#000").text(pdfSafe(header.title), MARGIN, MARGIN, { width, lineBreak: false });
    doc.font(BODY_FONT).fontSize(8).fillColor("#333");
    let y = MARGIN + 16;
    for (const line of header.lines) {
      doc.text(fit(doc, pdfSafe(line), width), MARGIN, y, { width, lineBreak: false });
      y += 10;
    }
    doc.moveTo(MARGIN, y + 2).lineTo(MARGIN + width, y + 2).strokeColor("#999").lineWidth(0.5).stroke();
    return y + 8;
  };

  const drawColumnHeader = (y: number, table: PdfTable, widths: number[]) => {
    doc.font(HEADER_FONT).fontSize(FONT_SIZE).fillColor("#000");
    let x = MARGIN;
    table.columns.forEach((c, i) => {
      doc.text(fit(doc, headerLabel(c.key), widths[i]! - 3), x, y, { width: widths[i]! - 3, lineBreak: false });
      x += widths[i]!;
    });
    doc.moveTo(MARGIN, y + ROW_HEIGHT - 2).lineTo(MARGIN + width, y + ROW_HEIGHT - 2).strokeColor("#ccc").lineWidth(0.5).stroke();
    return y + ROW_HEIGHT;
  };

  let y = drawHeader();
  for (const [index, table] of tables.entries()) {
    const widths = columnWidths(doc, table, width);
    if (index > 0 && y + ROW_HEIGHT * 4 > bottom()) { doc.addPage(); y = drawHeader(); }
    if (table.heading) {
      doc.font(HEADER_FONT).fontSize(9).fillColor("#000").text(pdfSafe(table.heading), MARGIN, y + 4, { width, lineBreak: false });
      y += 16;
    }
    y = drawColumnHeader(y, table, widths);
    if (table.rows.length === 0) {
      doc.font(BODY_FONT).fontSize(FONT_SIZE).fillColor("#555").text(pdfSafe(table.emptyText), MARGIN, y, { width, lineBreak: false });
      y += ROW_HEIGHT;
    }
    for (const row of table.rows) {
      if (y > bottom()) { doc.addPage(); y = drawColumnHeader(drawHeader(), table, widths); }
      doc.font(BODY_FONT).fontSize(FONT_SIZE).fillColor("#000");
      let x = MARGIN;
      table.columns.forEach((c, i) => {
        const text = pdfSafe(formatCell(c.kind, row[c.key]));
        doc.text(fit(doc, text, widths[i]! - 3), x, y, { width: widths[i]! - 3, lineBreak: false });
        x += widths[i]!;
      });
      y += ROW_HEIGHT;
    }
    y += ROW_HEIGHT;
  }

  // Footer pass. Writing below the bottom margin makes pdfkit add a page, so the margin is lifted
  // for the footer line and restored.
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const saved = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    doc.font(BODY_FONT).fontSize(8).fillColor("#333")
      .text(pdfSafe(options.pageLabel(i - range.start + 1, range.count)), MARGIN, doc.page.height - MARGIN + 8, { width, align: "right", lineBreak: false });
    doc.page.margins.bottom = saved;
  }
  doc.end();
  return done;
}

/** The PDF header lines (shared by the on-screen export and the package): tenant · shop · range · generated at (ET) · generated by. */
export function pdfHeaderLines(language: Language, args: { shop: string; from: string; to: string; at: Date; by: string }): string[] {
  const t = (key: TranslationKey, values?: Record<string, string | number>) => serverT(language, key, values);
  return [
    TENANT_NAME,
    t("reports.export.header.shop", { shop: args.shop }),
    t("reports.export.header.range", { from: args.from, to: args.to }),
    t("reports.export.header.generated_at", { date: etCalendarDate(args.at.toISOString()), time: formatTime(args.at.toISOString(), language) }),
    t("reports.export.header.generated_by", { name: args.by }),
  ];
}
