/**
 * build-cards — the exported cards, by slug. The JSON files are GENERATED by
 * scripts/export-build-card.ts from the build sheet; never hand-edit them
 * (tests/training-build-card.test.ts fails when one drifts from the sheet).
 */

import crunchyBoi from "./build-cards/crunchy-boi.card.json";
import type { BuildCard } from "./build-card-shared";

const CARDS: Record<string, BuildCard> = {
  "crunchy-boi": crunchyBoi as BuildCard,
};

export function buildCardForSlug(slug: string): BuildCard | null {
  return Object.hasOwn(CARDS, slug) ? (CARDS[slug] ?? null) : null;
}
