/**
 * co-scenes-shared — where the vendored <crunchy-build> bundle lives, and the
 * narrow surface this app uses from it. Client-safe (a JSON import, no I/O).
 *
 * The bundle is co-scenes' hashed web build, vendored by
 * scripts/vendor-co-scenes.ts into vendor/co-scenes/dist/ (NOT public/) and
 * pinned in vendor/co-scenes/VERSION. The hashed filenames make every URL immutable, so
 * a re-vendor can never serve a stale chunk under an old name.
 *
 * The training entry exports `trainingSceneFactory(steps, dataUrl)`: track C's
 * REAL-PHOTO C1 scene (stage-show), Juan-approved round 3. `drawn` comes from
 * the scene's own look plan, so C1 shows no "Illustrated" badge; if the photos
 * are unreachable the entry falls back to track C's drawn studio look, marked
 * illustrated. The swap lives INSIDE co-scenes (web/training-entry.ts); here it
 * is a re-vendor (scripts/vendor-co-scenes.ts).
 *
 * TWO KINDS OF VENDORED FILE, one manifest:
 *   - `files`  — code + data, COMMITTED under vendor/co-scenes/dist/;
 *   - `photos` — the real food photos, NEVER committed (the photo rule). In a
 *     deploy they live in the private `training-assets` bucket (0212) and the
 *     authenticated route 302s to a 60 s signed URL; locally the vendor script
 *     also drops them in the git-ignored vendor/co-scenes/photos/ (dev store).
 *     docs/runbooks/training-assets.md.
 */

import rawManifest from "@/vendor/co-scenes/dist/asset-manifest.json";

export interface CoScenesManifest {
  entries: { training: string; data?: string };
  files: Record<string, string>;
  photos?: Record<string, string>;
}
const manifest = rawManifest as CoScenesManifest;

import type { WebStep } from "./build-card-shared";

/** Served by app/api/training/co-scenes/[...path]/route.ts, behind full session validation. */
export const CO_SCENES_BASE = "/api/training/co-scenes/";

/**
 * The manifest's own allowlist: a request path is an asset only if it is a key
 * of `files` (hash-checked by tests/co-scenes-vendor.test.ts). Returns the
 * content type to serve it with, or null. Pure, so the gate is testable.
 */
export interface CoScenesAssetRef {
  /** Path under its store: dist/<rel> for files, photos/<name> for photos. */
  rel: string;
  store: "dist" | "photos";
  contentType: string;
  sha256: string;
}

const PHOTO_PREFIX = "photos/";
/** A photo name: `<asset id>-<sha256>.png`, one path segment, no dot-leading id (same shape the upload enforces). */
const PHOTO_NAME = /^[A-Za-z0-9_-][A-Za-z0-9._-]*-([0-9a-f]{64})\.png$/;
/** A dist path: `/`-separated segments of safe characters; no empty, `.` or `..` segment, no backslash. */
const DIST_SEGMENT = /^[A-Za-z0-9_-][A-Za-z0-9._-]*$/;

/**
 * The SHAPE gate, enforced here and again at the filesystem join
 * (lib/training/co-scenes-files.ts): manifest membership alone is not trusted,
 * because the manifest is generated by another tool.
 */
/** Exactly one photo name: `<id>-<sha256>.png`, a single segment. */
export function isPhotoName(name: string): boolean {
  return PHOTO_NAME.test(name);
}

export function isSafeDistPath(rel: string): boolean {
  const segs = rel.split("/");
  return segs.length > 0 && segs.every((s) => DIST_SEGMENT.test(s));
}

export function coScenesAsset(rel: string, m: CoScenesManifest = manifest): CoScenesAssetRef | null {
  if (rel.startsWith(PHOTO_PREFIX)) {
    const name = rel.slice(PHOTO_PREFIX.length);
    const photos = m.photos ?? {};
    const shape = PHOTO_NAME.exec(name);
    if (!shape || !Object.hasOwn(photos, name)) return null;
    const sha256 = photos[name];
    // The name is content-addressed: the sha256 it carries must be the manifest's.
    return sha256 && sha256 === shape[1] ? { rel: name, store: "photos", contentType: "image/png", sha256 } : null;
  }
  if (!isSafeDistPath(rel) || !Object.hasOwn(m.files, rel)) return null;
  const sha256 = m.files[rel];
  if (!sha256) return null;
  if (rel.endsWith(".js")) return { rel, store: "dist", contentType: "text/javascript; charset=utf-8", sha256 };
  if (rel.endsWith(".json")) return { rel, store: "dist", contentType: "application/json; charset=utf-8", sha256 };
  return null;
}

/** URL of the scene data file (steps, layout, photo list), when the bundle carries one. */
export const CO_SCENES_DATA_URL: string | null = manifest.entries.data ? `/api/training/co-scenes/${manifest.entries.data}` : null;

/** The strong ETag of an asset: its manifest sha256, quoted. */
export function coScenesEtag(sha256: string): string {
  return `"${sha256}"`;
}

/**
 * Whether an If-None-Match header matches this strong ETag (RFC 9110: a
 * comma-separated list, or "*"). Weak validators never match a strong ETag.
 */
export function ifNoneMatchHits(header: string | null, etag: string): boolean {
  if (!header) return false;
  return header.split(",").some((t) => {
    const v = t.trim();
    return v === "*" || v === etag;
  });
}

/** URL of the training entry module, from the vendored manifest. */
export const CO_SCENES_TRAINING_URL = `${CO_SCENES_BASE}${manifest.entries.training}`;

type SceneFactory = (canvas: HTMLCanvasElement, opts: { look: "stage" | "studio"; quality: "phone" | "full" }) => unknown;

/** The element instance, as far as this app touches it. */
export interface CrunchyBuildElementLike extends HTMLElement {
  factory: SceneFactory | null;
  setStep(n: number): void;
  ready(): Promise<unknown>;
}

export interface CrunchyStepEventDetail {
  step: number;
  mode: string;
  illustrated: boolean;
}

/** The training entry's exports. */
export interface CoScenesTraining {
  defineTrainingElement(tag?: string): void;
  trainingSceneFactory(steps: readonly WebStep[], dataUrl: string): SceneFactory;
}

let loading: Promise<CoScenesTraining> | null = null;

/** Loads the vendored bundle once per page. A failed load is not cached, so the next mount (e.g. a language switch) retries. */
export function loadCoScenesTraining(): Promise<CoScenesTraining> {
  loading ??= (
    import(/* webpackIgnore: true */ /* turbopackIgnore: true */ CO_SCENES_TRAINING_URL) as Promise<CoScenesTraining>
  ).catch((e: unknown) => {
    loading = null;
    throw e;
  });
  return loading;
}
