-- Migration 0137_catering_prep_demand
-- Applied via Supabase MCP apply_migration on 2026-07-19.
-- Canonical reference: docs/superpowers/specs/2026-07-19-w4a-catering-prep-demand-design.md
--                      + lib/catering/prep-demand.ts
--
-- W4a: an append-only ledger of prep demand generated by confirmed catering leads.
-- One row per resolved prep unit. reserve on stage->confirmed; consume on ->out/completed;
-- release on revert/lost. 3-way XOR ref: a resolved item, a resolved menu_item, or an
-- UNRESOLVED W1b choice slot (choice_package_item_id).

CREATE TABLE public.catering_prep_demand (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pipeline_id             uuid NOT NULL REFERENCES public.catering_pipeline(id),
  quote_id                uuid NOT NULL REFERENCES public.catering_quotes(id),
  location_id             uuid NOT NULL REFERENCES public.locations(id),
  need_date               date NOT NULL,
  item_id                 uuid REFERENCES public.items(id),
  menu_item_id            uuid REFERENCES public.menu_items(id),
  choice_package_item_id  uuid REFERENCES public.catering_package_items(id),
  portion                 text CHECK (portion IN ('quarter','half','whole')),
  qty                     numeric NOT NULL CHECK (qty > 0),
  status                  text NOT NULL DEFAULT 'reserved' CHECK (status IN ('reserved','consumed','released')),
  created_at              timestamptz NOT NULL DEFAULT now(),
  created_by              uuid REFERENCES public.users(id),
  consumed_at             timestamptz,
  CONSTRAINT catering_prep_demand_one_ref CHECK (
    (item_id IS NOT NULL)::int + (menu_item_id IS NOT NULL)::int + (choice_package_item_id IS NOT NULL)::int = 1
  )
);

-- The overlay read: reserved demand at a location over a date window.
CREATE INDEX catering_prep_demand_overlay
  ON public.catering_prep_demand (location_id, need_date) WHERE status = 'reserved';
-- Lifecycle ops key off the lead.
CREATE INDEX catering_prep_demand_pipeline
  ON public.catering_prep_demand (pipeline_id);

ALTER TABLE public.catering_prep_demand ENABLE ROW LEVEL SECURITY;
-- Read: owner/cgs (>=9) globally, or staff whose locations include the row's location.
CREATE POLICY catering_prep_demand_read ON public.catering_prep_demand FOR SELECT
  USING (
    public.current_user_role_level() >= 9
    OR location_id = ANY (public.current_user_locations())
  );
-- Writes are service-role only (the lib is the authority) — deny all end-user writes.
CREATE POLICY catering_prep_demand_no_user_insert ON public.catering_prep_demand FOR INSERT WITH CHECK (false);
CREATE POLICY catering_prep_demand_no_user_update ON public.catering_prep_demand FOR UPDATE USING (false);
CREATE POLICY catering_prep_demand_no_user_delete ON public.catering_prep_demand FOR DELETE USING (false);
